config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root to: 'events#home'
  resources :events
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/event.rb
# frozen_string_literal: true

class Event < ApplicationRecord
  validates :name, presence: true
  validates :date, presence: true
  validates :description, presence: true, length: { maximum: 300 }
  validates :email, presence: true
  scope :get_coming, -> { where('date >= ?', Date.today) }
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base; end

app/controllers/events_controller.rb
# frozen_string_literal: true

class EventsController < ApplicationController
  before_action :set_event, only: %i[show edit update destroy]
  helper_method :sort_column, :sort_direction
  # GET /events
  # GET /events.json
  def index
    @events = Event.order(sort_column + ' ' + sort_direction).get_coming
  end

  # GET /events/1
  # GET /events/1.json
  def show; end

  # GET /events/new
  def new
    @event = Event.new
  end

  # GET /events/1/edit
  def edit; end

  # POST /events
  # POST /events.json
  def create
    @event = Event.new(event_params)

    respond_to do |format|
      if @event.save
        format.html do
          redirect_to @event, notice: 'Event was successfully created.'
        end
        format.json { render :show, status: :created, location: @event }
      else
        format.html { render :new }
        format.json do
          render json: @event.errors, status: :unprocessable_entity
        end
      end
    end
  end

  # PATCH/PUT /events/1
  # PATCH/PUT /events/1.json
  def update
    respond_to do |format|
      if @event.update(event_params)
        format.html do
          redirect_to @event, notice: 'Event was successfully updated.'
        end
        format.json { render :show, status: :ok, location: @event }
      else
        format.html { render :edit }
        format.json do
          render json: @event.errors, status: :unprocessable_entity
        end
      end
    end
  end

  # DELETE /events/1
  # DELETE /events/1.json
  def destroy
    @event.destroy
    respond_to do |format|
      format.html do
        redirect_to events_url, notice: 'Event was successfully destroyed.'
      end
      format.json { head :no_content }
    end
  end

  private

  def sort_column
    Event.column_names.include?(params[:sort]) ? params[:sort] : 'date'
  end

  def sort_direction
    %w[asc desc].include?(params[:direction]) ? params[:direction] : 'asc'
  end

  # Use callbacks to share common setup or constraints between actions.
  def set_event
    @event = Event.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def event_params
    params.require(:event).permit(:name, :date, :description, :email)
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper; end

app/helpers/events_helper.rb
# frozen_string_literal: true

module EventsHelper
  def sortable(column, title = nil)
    title ||= column.titleize
    css_class = column == sort_column ? "current #{sort_direction}" : nil
    direction =
      column == sort_column && sort_direction == 'asc' ? 'desc' : 'asc'
    link_to title, { sort: column, direction: direction }, class: css_class
  end
end

app/views/events/_form.html.erb
<%= form_with(model: event, local: true) do |form| %>
  <% if event.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(event.errors.count, "error") %> prohibited this event from being saved:</h2>

      <ul>
      <% event.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group row">
    <div class="col-sm-2">
      <%= form.label :name, class: "col-form-label" %>
    </div>
    <div class="col-sm-6">
      <%= form.text_field :name, required: true,
                          placeholder:"Event name required",
                          class: "form-control form-control-sm " %>
    </div>
  </div>

  <div class="form-group row">
    <div class="col-sm-2">
      <%= form.label :date %>
    </div>
    <div class="col-sm-6">
      <%= form.datetime_select :date, class:"form-control input-sm"  %>
    </div>
  </div>

  <div class="form-group row">
    <div class="col-md-2">
      <%= form.label :description %>
    </div>
    <div class="col-sm-6">
      <%= form.text_area :description,
                         required: true,
                         placeholder:"Description required",
                         class:"form-control", rows:"3",
                         maxlength: 300 %>
    </div>
  </div>

  <div class="form-group row">
    <div class="col-md-2">
      <%= form.label :email %>
    </div>
    <div class="col-sm-6">
      <%= form.text_field :email,
                          required: true,
                          class: "form-control form-control-sm",
                          placeholder:"Enter your email", type: "email" %>
    </div>
  </div>

    <div class="">
      <div class="actions">
        <%= form.submit nil, :class => "btn btn-secondary btn-sm active" %>
      </div>
    </div>
  </div>

<% end %>

app/views/events/edit.html.erb
<p id="notice"><%= notice %></p>

<h2 class="display-5 text-center p-2 mb-2 bg-secondary text-white rounded-pill">Editing Event</h2>

<%= render 'form', event: @event %>

<div class="col-md-16">
  <ul class="nav">
    <div style="margin-right: 2px">
      <li class="nav-item">
        <%= link_to 'Back', events_path, :class => "btn btn-secondary btn-sm active" %>
      </li>
    </div>
  </ul>
</div>

app/views/events/home.html.erb
<div class="jumbotron">
  <div class="container">
    <h1 class="display-4">Welcome to Codeur-Events</h1>
    <p class="lead">Codeur-Events allows you to create and manage your favorite events.</p>
    <p class="lead">Enjoy it!</p>
  </div>
</div>

app/views/events/index.html.erb
<p id="notice"><%= notice %></p>

<h2 class="display-5 text-center p-2 mb-2 bg-secondary text-white rounded-pill">My Events</h2>

<div class="table-responsive-md">
  <table id="events" class="table table-hover table-sm table-bordered">
    <thead class="table-active">
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Email</th>
      <th><%= sortable "date", "Event Date" %></th>
      <th><%= sortable "created_at", "Created At" %></th>
      <th colspan="3">Options</th>
    </tr>
    </thead>

    <tbody>
    <% @events.each do |event| %>
      <tr>
        <td class="<%= "red" if  Date.today+10 >= event.date %>"><%= event.name %></td>
        <td><%= event.description %></td>
        <td><%= event.email %></td>
        <td><%= event.date.strftime("%e %B %Y, %H:%M") %></td>
        <td><%= event.created_at.strftime("%e %B %Y, %H:%M") %></td>
        <td><%= link_to 'Show', event %></td>
        <td><%= link_to 'Edit', edit_event_path(event) %></td>
        <td><%= link_to 'Destroy', event, method: :delete, data: {confirm: 'Are you sure?'} %></td>
      </tr>
    <% end %>
    </tbody>
  </table>
  <br>
</div>

app/views/events/new.html.erb
<p id="notice"><%= notice %></p>

<h2 class="display-5 text-center p-2 mb-2 bg-secondary text-white rounded-pill">Create Event</h2>

<%= render 'form', event: @event %>

app/views/events/show.html.erb
<p id="notice"><%= notice %></p>

<h2 class="display-5 text-center p-2 mb-2 bg-secondary text-white rounded-pill">Show Event</h2>

<div class="card bg-light mb-3" style="max-width: 18rem;">
  <div class="card-header"><%= @event.name %></div>
  <div class="card-body">
    <p>
      <strong>Name:</strong>
      <%= @event.name %>
    </p>

    <p>
      <strong>Date:</strong>
      <%= @event.date %>
    </p>

    <p>
      <strong>Description:</strong>
      <%= @event.description %>
    </p>

    <p>
      <strong>Email:</strong>
      <%= @event.email %>
    </p>

  </div>
</div>

<div class="col-md-16">
  <ul class="nav">
    <div style="margin-right: 2px">
      <li class="nav-item">
        <%= link_to 'Edit', edit_event_path(@event), :class => "btn btn-secondary btn-sm active" %>
      </li>
    </div>
    <div style="margin-right: 2px">
      <li class="nav-item">
        <%= link_to 'Back', events_path, :class => "btn btn-secondary btn-sm active" %>
      </li>
    </div>
  </ul>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Codeur-Events</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <div class="container-fluid">
    <ul class="nav nav-pills justify-content-end">
      <li><%= link_to 'Home', root_path, class: "nav-link " %></li>
      <li><%= link_to 'Create Event', new_event_path, class: "nav-link" %></li>
      <li><%= link_to 'My Events', events_path, class: "nav-link" %></li>
    </ul>
  </div>
  <br>
    <%= yield %>
  </body>
</html>